import { IsString, IsNotEmpty, IsDateString } from 'class-validator';
import { Expose } from 'class-transformer';
import { ApiProperty } from '@nestjs/swagger';
import { ApiInternal } from '../../common/decorators';

/**
 * Auto-generated fields for Feedback Response
 * Fields that are automatically generated by the database/system
 */
@ApiInternal()
export class FeedbackGeneratedFieldsDto {
    @ApiProperty({
        example: '550e8400-e29b-41d4-a716-446655440000',
        format: 'uuid',
        description:
            "Feedback collection unique identifier (UUID). Auto-generated UUID primary key. Format: standard UUID v4 (e.g., '550e8400-e29b-41d4-a716-446655440000').",
    })
    @Expose()
    @IsString()
    @IsNotEmpty()
    public id!: string;

    @ApiProperty({
        example: '2026-01-10T10:30:00.000Z',
        format: 'date-time',
        description:
            "Feedback collection creation timestamp. Automatically set when collection is created. Format: ISO 8601 timestamp (e.g., '2026-01-10T10:30:00.000Z').",
    })
    @Expose()
    @IsDateString()
    public createdAt!: Date;

    @ApiProperty({
        example: '2026-01-10T10:30:00.000Z',
        format: 'date-time',
        description:
            "Feedback collection last update timestamp. Automatically updated when collection is modified. Format: ISO 8601 timestamp (e.g., '2026-01-10T10:30:00.000Z').",
    })
    @Expose()
    @IsDateString()
    public updatedAt!: Date;
}
